import {useState} from 'react';
import {Pickaxe,ArrowRight,ChevronRight,Pause,Play,ShieldCheck,Compass,LoaderCircle} from 'lucide-react';
import {Link} from 'react-router-dom';
import {Button} from '../components/ui/button';
import {Agent,stageNames} from './types';
import {Avatar} from './Avatar';
import {request} from './api';
import {toast} from 'sonner';
export const AgentPanel=({agent,onCreate,onChange,large=false}:{agent:Agent|null;onCreate:()=>void;onChange:(a:Agent)=>void;large?:boolean})=>{
 const [busy,setBusy]=useState(false);
 const action=async()=>{if(!agent)return;setBusy(true);const command=agent.status==='active'?'pause':agent.status==='ready'?'start':'resume';try{onChange(await request<Agent>('/agent/action',{method:'POST',body:JSON.stringify({action:command})}));toast.success(command==='pause'?'Your agent is taking a break.':'Your agent is on shift.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}};
 return <section className={`agent-panel ${large?'agent-large':''}`} data-testid="my-agent-panel"><div className="panel-heading"><div className="section-title"><Pickaxe size={16}/><h2 data-testid="my-agent-heading">My Agent</h2></div>{agent&&<span className={`state-tag ${agent.status==='active'?'green':''}`} data-testid="agent-status">{agent.status==='active'?'ON SHIFT':agent.status==='paused'?'RESTING':'READY'}</span>}</div>
 {!agent?<div className="agent-empty"><div className="miner-portrait"><span/><Avatar size={100}/><span className="portrait-spark">+</span><span className="portrait-spark second">+</span></div><h3 data-testid="agent-empty-title">A little miner.<br/>A world of possibility.</h3><p data-testid="agent-empty-description">Your next great discovery<br/>starts right here.</p><Button data-testid="create-agent-button" className="gold-button full-width" onClick={onCreate}><Pickaxe size={15}/>Create agent<ArrowRight size={15}/></Button><span className="quiet-note" data-testid="agent-no-staking"><ShieldCheck size={12}/>No staking. No private keys.</span></div>:<div className="agent-summary"><div className={`agent-profile avatar-${agent.avatar}`}><Avatar avatar={agent.avatar} size={large?125:84}/><div><h3 data-testid="agent-name">{agent.name}</h3><span data-testid="agent-personality">{agent.personality} · {agent.preference==='deep'?'Deep explorer':agent.preference==='careful'?'Steady hand':'Wayfinder'}</span></div></div><div className="agent-task" data-testid="agent-current-task"><i className={agent.status==='active'?'status-dot':'paused-dot'}/>{agent.status==='paused'?'Taking a well-earned break':agent.status==='ready'?'Ready for the first expedition':stageNames[agent.stage]}</div><div className="agent-stats"><div><span>Ore collected</span><strong data-testid="agent-ore">{agent.ore.toLocaleString('en-US')}</strong></div><div><span>Expeditions</span><strong data-testid="agent-expeditions">{agent.expeditions.toLocaleString('en-US')}</strong></div></div><Button className={agent.status==='active'?'outline-button full-width':'gold-button full-width'} data-testid={agent.status==='active'?'pause-mining-button':'start-mining-button'} disabled={busy} onClick={action}>{busy?<LoaderCircle className="spin"/>:agent.status==='active'?<Pause size={15}/>:<Play size={15}/>} {agent.status==='active'?'Pause expedition':agent.status==='ready'?'Start mining':'Resume mining'}</Button>{!large&&<Link data-testid="view-agent-details" className="agent-link" to="/agent">Agent details<ChevronRight size={14}/></Link>}<p className="quiet-note" data-testid="agent-persistence"><Compass size={12}/>The expedition continues while you’re away.</p></div>}
 </section>;
};