import {useState,useEffect,useCallback} from 'react';
import {Link} from 'react-router-dom';
import {Trophy,Flag,Timer,Users,ShieldCheck,ArrowUpRight,Pickaxe,LoaderCircle,ChevronDown,Medal,Info} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';
import {Button} from '../components/ui/button';
import {Avatar} from './Avatar';
import {Agent} from './types';
import {LeaderboardData,LeaderRow} from './strategyTypes';
import {request} from './api';
import {toast} from 'sonner';
const rules=[['Equal starting resources','Every entry starts with 100% energy, 100% tool integrity, an empty cart, depth 1, and 600 decisions. Existing lifetime ore and collections remain yours.'],['A score you can account for','Score = delivered ore value + depth milestones − setbacks, with a floor of zero. Each new deepest level earns 10 points, up to 40 per run. Each mining setback deducts 25 points. Undelivered cargo earns no points.'],['Strategy, not spending','Risk, depth, vein quality, resource reserves, ore priority, and ordered IF/THEN rules all affect decisions. Maintenance and recovery consume actions. There are no paid boosts or holding-based advantages.'],['One entry. No resets.','One entry per agent per weekly season. Pausing stops decisions, not the UTC season clock. Editing a strategy keeps resources, spent actions, and scores intact. A completed run keeps its final score.'],['A fair field','All competitors receive the same deterministic environmental sequence by decision number. Strategies determine which risks they take. Ties use delivered ore, then fewer decisions, then earlier entry. Crew bots are excluded.'],['Prizes stay separate','Prize amounts, reward asset, payout rules, and project or sponsor funding will be announced separately. Holder fee allocations are never used. Browser profiles are not verified wallets; funded prizes require identity and eligibility checks.']];
export default function ContestPage({agent,onCreate,onChange}:{agent:Agent|null;onCreate:()=>void;onChange:(a:Agent)=>void}){
 const [data,setData]=useState<LeaderboardData|null>(null),[error,setError]=useState(''),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[openRule,setOpenRule]=useState<number|null>(0),[filter,setFilter]=useState(''),[now,setNow]=useState(Date.now()),[selected,setSelected]=useState<LeaderRow|null>(null);
 const load=useCallback(async()=>{try{setData(await request<LeaderboardData>('/contest/leaderboard'));setError('');}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{load();const poll=setInterval(load,6000),clock=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(poll);clearInterval(clock);};},[load]);
 const entered=!!agent?.contest&&agent.contest.season_id===data?.season.id;
 const remaining=data?Math.max(0,new Date(data.season.ends_at).getTime()-now):0;
 const timeLabel=data?`${Math.floor(remaining/86400000)}d ${String(Math.floor(remaining/3600000)%24).padStart(2,'0')}h ${String(Math.floor(remaining/60000)%60).padStart(2,'0')}m`:'—';
 const mine=data?.entries.find(r=>r.agent_id===agent?.id);
 const enter=async()=>{setBusy(true);try{const next=await request<Agent>('/contest/enter',{method:'POST'});onChange(next);setConfirm(false);load();toast.success('You are in. Your contest expedition has started.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}};
 const list=data?.entries.filter(r=>(r.name+' '+r.strategy_name).toLowerCase().includes(filter.toLowerCase()))||[];
 return <div className="page-content contest-page"><div className="page-title"><div><div className="eyebrow" data-testid="contest-eyebrow"><Trophy size={13}/>THE UNDERGROUND LEAGUE</div><h1 data-testid="contest-title">A little competitive<span>.</span></h1><p data-testid="contest-description">Same mine. Different minds. Let your strategy do the talking.</p></div><Link className="text-button" to="/strategy" data-testid="contest-strategy-link">Tune your strategy<ArrowUpRight size={15}/></Link></div>
 {error&&<div className="error-banner" role="alert" data-testid="contest-error"><span>{error}</span><button data-testid="contest-retry" onClick={load}>Retry</button></div>}
 <section className="season-banner" data-testid="contest-season"><div className="season-insignia"><Trophy size={34}/><span>01</span></div><div className="season-info"><span className="eyebrow" data-testid="season-id">WEEK OF {data?.season.id||'—'} · SOLANA COMMUNITY</span><h2 data-testid="season-title">{data?.season.name||'Brass Hollow Open'}</h2><p data-testid="season-description">600 decisions. One miner. Your playbook.</p></div><div className="season-countdown"><span data-testid="contest-countdown-label"><Timer size={13}/>SEASON CLOSES IN</span><strong data-testid="contest-countdown">{timeLabel}</strong><small data-testid="contest-close-date">{data?new Date(data.season.ends_at).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'})+' · 00:00 UTC':'—'}</small></div><Button className={entered?'outline-button':'gold-button'} data-testid="contest-enter-button" disabled={entered||!data||!!error} onClick={()=>agent?setConfirm(true):onCreate()}><Flag size={15}/>{entered?'Entry registered':agent?'Enter contest':'Create your contender'}</Button></section>
 <div className="contest-metrics"><div data-testid="contest-entries-metric"><Users size={19}/><span>Contenders<strong>{data?.total??'—'}</strong></span></div><div data-testid="contest-rank-metric"><Medal size={19}/><span>Your position<strong>{mine?`#${mine.rank}`:'Not entered'}</strong></span></div><div data-testid="contest-score-metric"><Pickaxe size={19}/><span>Your contest score<strong>{entered?(agent?.contest?.score||0).toLocaleString('en-US'):'—'}</strong></span></div><div data-testid="contest-prize-metric"><Trophy size={19}/><span>Separate prize pool<strong>To be announced</strong></span></div></div>
 {entered&&agent?.contest&&<div className="contest-run-status" data-testid="contest-run-status"><div><span>{agent.contest.status==='active'?'YOUR RUN IS IN PROGRESS':agent.contest.status==='completed'?'ACTION BUDGET COMPLETE':'SEASON CLOSED'}</span><b>{agent.contest.actions_used} / {data?.season.action_budget||600} decisions</b></div><div className="contest-progress"><i style={{width:`${Math.min(100,agent.contest.actions_used/6)}%`}}/></div><p data-testid="contest-score-breakdown">{agent.contest.banked_points} banked value + {agent.contest.exploration_points} depth points − {agent.contest.penalties} deductions <span>· {agent.status==='paused'?'Your miner is paused.':'Your strategy runs on the server.'}</span></p></div>}
 <div className="contest-layout"><section className="leaderboard-section"><div className="strategy-section-heading"><div className="section-title"><Trophy size={17}/><h2 data-testid="leaderboard-title">The leaderboard</h2><span className="tiny-live" data-testid="leaderboard-live">LIVE</span></div><input data-testid="leaderboard-search" aria-label="Find a contender" placeholder="Find a contender…" value={filter} onChange={e=>setFilter(e.target.value)}/></div><div className="leaderboard-table"><div className="leaderboard-table-heading" data-testid="leaderboard-columns"><span>RANK</span><span>MINER / STRATEGY</span><span>SCORE</span><span>DECISIONS</span></div>{list.length?list.map(row=><button key={row.agent_id} className={`leaderboard-row ${row.agent_id===agent?.id?'your-entry':''}`} data-testid={`leaderboard-entry-${row.agent_id}`} onClick={()=>setSelected(row)}><span className={`rank rank-${row.rank}`}>{row.rank<=3?<Medal size={17}/>:null}{String(row.rank).padStart(2,'0')}</span><span className="leaderboard-miner"><Avatar avatar={row.avatar} size={45}/><span><b>{row.name}{row.agent_id===agent?.id&&<i>YOU</i>}</b><small>{row.strategy_name}</small></span></span><strong>{row.score.toLocaleString('en-US')}</strong><span className="leaderboard-actions">{row.actions_used}<small>/ 600</small></span></button>):<div className="leaderboard-empty" data-testid="leaderboard-empty"><Trophy size={39}/><h3>{filter?'No matching contenders.':'The first place is still yours to chase.'}</h3><p>{filter?'Try another miner or strategy name.':'No entries yet. The resident crew cheers from the sidelines.'}</p>{!filter&&!entered&&<button className="text-button" data-testid="leaderboard-empty-enter" onClick={()=>agent?setConfirm(true):onCreate()}>Enter the open<ArrowUpRight size={14}/></button>}</div>}</div><p className="fine-print" data-testid="leaderboard-ranking-note">Ranked by score, delivered ore, then fewer decisions. Crew bots never compete. Top 100 entries shown.</p></section>
 <aside className="contest-rules"><div className="section-title"><ShieldCheck size={17}/><h2 data-testid="contest-rules-title">The ground rules</h2></div>{rules.map(([title,text],i)=><div className={`contest-rule-item ${openRule===i?'open':''}`} key={title}><button data-testid={`contest-rule-toggle-${i}`} aria-expanded={openRule===i} onClick={()=>setOpenRule(openRule===i?null:i)}>{title}<ChevronDown size={15}/></button>{openRule===i&&<p data-testid={`contest-rule-content-${i}`}>{text}</p>}</div>)}<div className="contest-prize-note" data-testid="contest-prize-notice"><Info size={16}/><p>Prizes are not funded or claimable yet. The holder pool is never part of the contest budget.</p></div></aside></div>
 <Dialog open={confirm} onOpenChange={v=>{if(!busy)setConfirm(v);}}><DialogContent className="mine-dialog" data-testid="contest-enter-dialog"><div className="dialog-emblem"><Flag size={25}/></div><DialogTitle data-testid="contest-enter-title">Put your strategy to work.</DialogTitle><DialogDescription data-testid="contest-enter-description">One entry for this season. A fresh resource budget, 600 decisions, and no score resets.</DialogDescription><div className="contest-confirm-details" data-testid="contest-entry-summary"><span>Miner<b>{agent?.name}</b></span><span>Strategy<b>{agent?.strategy_name} · v{agent?.strategy_version}</b></span><span>Entry fee<b>None</b></span><span>Prize pool<b>To be announced</b></span></div><p className="access-note" data-testid="contest-entry-note">Entering starts your agent and resets only its working resources. Lifetime ore and discoveries stay intact. Browser access is not verified wallet ownership; future funded prizes require eligibility verification.</p><Button className="gold-button full-width" data-testid="contest-confirm-enter" disabled={busy} onClick={enter}>{busy?<LoaderCircle size={15} className="spin"/>:<Flag size={15}/>}Enter and start mining</Button></DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent className="mine-dialog" data-testid="leaderboard-details-dialog">{selected&&<><div className="crew-dialog-profile"><Avatar avatar={selected.avatar} size={80}/><div><span className="eyebrow">RANK #{selected.rank}</span><DialogTitle data-testid="leaderboard-details-name">{selected.name}</DialogTitle><DialogDescription>{selected.strategy_name}</DialogDescription></div></div><div className="contest-confirm-details" data-testid="leaderboard-entry-details">{[['Contest score',selected.score],['Ore delivered',selected.delivered],['Decisions used',`${selected.actions_used} / 600`],['Setbacks',selected.incidents],['Entry status',selected.status]].map(([k,v])=><span key={k}>{k}<b>{v}</b></span>)}</div><p className="access-note">Strategy rules remain private to the agent owner. This score has no effect on holder rewards.</p></>}</DialogContent></Dialog>
 </div>;
}