import {useEffect,useState} from 'react';
import {Wallet,ShieldCheck,Pickaxe,BookOpen,ArrowRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';
import {Button} from '../components/ui/button';
import {Agent,JournalEvent,stageNames} from './types';
import {Avatar} from './Avatar';
import {request} from './api';
export const WalletDialog=({open,onClose}:{open:boolean;onClose:()=>void})=><Dialog open={open} onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="mine-dialog wallet-dialog" data-testid="wallet-dialog"><div className="dialog-emblem"><Wallet size={25}/></div><DialogTitle data-testid="wallet-dialog-title">Your wallet. Always yours.</DialogTitle><DialogDescription data-testid="wallet-dialog-description">Wallet connections open after token and network verification. The underground is open to explore in the meantime.</DialogDescription><dl className="wallet-checks"><div data-testid="wallet-token-status"><dt>MINEPX token</dt><dd>Not launched</dd></div><div data-testid="wallet-network-status"><dt>Network</dt><dd>Robinhood Chain</dd></div><div data-testid="wallet-gld-status"><dt>GLD reward contract</dt><dd>Awaiting verification</dd></div></dl><p className="access-note" data-testid="wallet-security-note"><ShieldCheck size={16}/>No staking, token approval, or private keys required to explore.</p><Button className="gold-button full-width" data-testid="wallet-return-button" onClick={onClose}>Back to the mine<ArrowRight size={16}/></Button></DialogContent></Dialog>;
export const CrewDialog=({agent,onClose}:{agent:Agent|null;onClose:()=>void})=>{
 const [events,setEvents]=useState<JournalEvent[]>([]),[error,setError]=useState('');
 const agentId=agent?.id,agentStep=agent?.step;
 useEffect(()=>{setEvents([]);setError('');if(!agentId)return;let live=true;request<JournalEvent[]>(`/journal?agent_id=${agentId}&limit=4`).then(d=>{if(live)setEvents(d);}).catch(()=>{if(live)setError('Field reports could not be loaded.');});return()=>{live=false;};},[agentId,agentStep]);
 return <Dialog open={!!agent} onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="mine-dialog crew-dialog" data-testid="crew-details-dialog">{agent&&<><div className="crew-dialog-profile"><Avatar avatar={agent.avatar} size={95}/><div><span className="bot-tag" data-testid="crew-details-type">{agent.is_bot?'CREW BOT':'MINER'}</span><DialogTitle data-testid="crew-details-name">{agent.name}</DialogTitle><DialogDescription data-testid="crew-details-personality">{agent.personality} by nature. A miner at heart.</DialogDescription></div></div><div className="agent-task" data-testid="crew-details-stage"><Pickaxe size={15}/>{agent.status==='active'?stageNames[agent.stage]:agent.status==='paused'?'Resting':'At basecamp'}</div><div className="agent-stats"><div><span>Ore collected</span><strong data-testid="crew-details-ore">{agent.ore}</strong></div><div><span>Expeditions</span><strong data-testid="crew-details-expeditions">{agent.expeditions}</strong></div></div><div className="section-title"><BookOpen size={15}/><h2>Latest field reports</h2></div>{error&&<p className="form-error" data-testid="crew-journal-error">{error}</p>}{events.map(e=><div className="crew-report" key={e.id} data-testid={`crew-report-${e.id}`}><p>“{e.message}”</p><time>{new Date(e.created_at).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'})}</time></div>)}{!events.length&&!error&&<p data-testid="crew-reports-empty">The next field report is on its way.</p>}{agent.is_bot&&<p className="access-note" data-testid="crew-financial-note">A resident crew bot. Its ore and expeditions are part of the mine’s story, not financial rewards.</p>}</>}</DialogContent></Dialog>;
};