import {useState} from 'react';
import {BookOpen,Compass,Pickaxe,Truck,Flame,Wrench,Tent,ChevronDown,Gem,LockKeyhole,Check} from 'lucide-react';
import {Agent} from './types';
const catalog=[{id:'pyrite',name:'Pyrite cluster',kind:'THE FIRST GLINT',color:'#cfad67',cycles:1,description:'Not everything that glitters is gold. Flint insists this one has character.'},{id:'quartz',name:'Smoky quartz',kind:'A QUIET DISCOVERY',color:'#abbab9',cycles:3,description:'A clear little crystal, tucked away where the lantern light barely reaches.'},{id:'azurite',name:'Azurite bloom',kind:'FROM THE DEEP',color:'#6fa8b3',cycles:6,description:'A splash of blue in a world of stone. Proof there is always more to discover.'}];
export const Collection=({agent}:{agent:Agent|null})=><div className="collection-grid">{catalog.map((c,i)=>{const unlocked=agent?.discoveries.includes(c.id);return <article className={`collection-item ${unlocked?'unlocked':''}`} key={c.id} data-testid={`collection-${c.id}`}><div className="crystal-art" style={{'--crystal-color':c.color} as React.CSSProperties}><i/><i/><i/><i/><i/></div><span className="eyebrow">{c.kind}</span><h3>{c.name}</h3><p>{c.description}</p><span className="collection-unlock" data-testid={`collection-status-${c.id}`}>{unlocked?<Check size={12}/>:<LockKeyhole size={12}/>} {unlocked?'Discovered':`${c.cycles} completed expedition${c.cycles>1?'s':''}`}</span></article>;})}</div>;
const faqs=[['Does my agent keep working when I leave?','Yes. Active agents run on the server, not in your browser. Your expedition clock, ore, discoveries, and journal are saved. Pausing your agent stops the expedition until you resume.'],['Do ore or discoveries increase my GLD share?','No. Ore, expedition progress, exploration styles, and discoveries are game-only. GLD shares depend solely on eligible MINEPX balance accumulated over holding time after activation.'],['Do I need a wallet to visit the mine?','No. The shared mine is public. You can create an agent using access saved in this browser. Keep that browser data to retain access. Wallet linking will become available after official contract verification.'],['What happens when someone sells their MINEPX?','Selling all MINEPX stops future reward accrual. It does not erase previously recorded allocations. Transfer history, not a single browser snapshot, determines eligible holding weight.'],['What funds the mining pool?','Only trading fees actually received and allocated to the pool. GLD pair support, fee denomination, recipient, allocation percentage, and post-graduation mechanics must be verified. No funding means no new rewards.'],['Are there monsters, boosts, or staking?','No monsters, paid boosts, token burning, staking, or minimum holding requirements. Exploration is about stories and discoveries, not paying for a financial advantage.']];
export default function Guide({agent}:{agent:Agent|null}){
 const [open,setOpen]=useState<number|null>(0);
 return <div className="page-content"><div className="page-title"><div><div className="eyebrow" data-testid="guide-eyebrow">NOTES FROM BELOW</div><h1 data-testid="guide-title">The Field Guide<span>.</span></h1><p data-testid="guide-description">A life underground, one small discovery at a time.</p></div><BookOpen className="page-symbol" size={36}/></div><section className="guide-cycle"><h2 data-testid="cycle-title">The rhythm of the mine</h2><div className="cycle-flow">{[{icon:Tent,title:'Basecamp',description:'Pack supplies.'},{icon:Compass,title:'Survey',description:'Find a promising seam.'},{icon:Pickaxe,title:'Mine',description:'Uncover the ore.'},{icon:Truck,title:'Haul',description:'Bring the cart home.'},{icon:Flame,title:'Refine',description:'Deliver the haul.'},{icon:Wrench,title:'Maintain',description:'Care for the tools.'}].map((s,i)=><div key={s.title} data-testid={`cycle-step-${i}`}><span className="cycle-number">0{i+1}</span><s.icon size={25}/><h3>{s.title}</h3><p>{s.description}</p></div>)}</div></section><section className="collection-section"><div className="collection-heading"><div className="section-title"><Gem size={19}/><h2 data-testid="collection-title">The discovery cabinet</h2></div><span className="neutral-badge" data-testid="collection-count">{agent?.discoveries.length||0} / 3 discovered</span></div><Collection agent={agent}/><p className="fine-print" data-testid="collection-financial-note">Collected for the story, not for financial advantage. Discoveries never multiply GLD rewards.</p></section><section className="faq-section"><div><span className="eyebrow">A FEW THINGS TO KNOW</span><h2 data-testid="faq-title">Before you head<br/>underground.</h2></div><div>{faqs.map(([question,answer],i)=><div className={`faq-item ${open===i?'open':''}`} key={i}><button data-testid={`faq-question-${i}`} onClick={()=>setOpen(open===i?null:i)} aria-expanded={open===i}>{question}<ChevronDown size={17}/></button>{open===i&&<p data-testid={`faq-answer-${i}`}>{answer}</p>}</div>)}</div></section></div>;
}