import {useState,useEffect} from 'react';
import {BookOpen,ArrowUpRight,Radio,Filter} from 'lucide-react';
import {JournalEvent,Agent,stageNames} from './types';
import {Avatar} from './Avatar';
import {request} from './api';
export const Journal=({events,agent,expanded=false}:{events:JournalEvent[];agent:Agent|null;expanded?:boolean})=>{
 const [scope,setScope]=useState('all'),[mine,setMine]=useState<JournalEvent[]>([]),[error,setError]=useState(''),[more,setMore]=useState(false);
 useEffect(()=>{if(scope!=='mine'||!agent)return;let live=true;request<JournalEvent[]>(`/journal?agent_id=${agent.id}&limit=50`).then(d=>{if(live){setMine(d);setError('');}}).catch(()=>{if(live)setError('The journal could not be loaded.');});return()=>{live=false;};},[scope,agent,events]);
 const list=scope==='mine'?mine:events;
 return <section className={`journal-section ${expanded?'journal-expanded':''}`} data-testid="agent-journal"><div className="panel-heading"><div className="section-title"><BookOpen size={16}/><h2 data-testid="journal-heading">Agent Journal</h2><span className="tiny-live" data-testid="journal-live">LIVE</span></div><div className="small-tabs"><button data-testid="journal-all-tab" className={scope==='all'?'active':''} onClick={()=>setScope('all')}>All activity</button><button data-testid="journal-mine-tab" className={scope==='mine'?'active':''} onClick={()=>setScope('mine')}>My agent</button></div></div>
 {error&&<p className="form-error" data-testid="journal-error">{error}</p>}<div className="journal-entries">{scope==='mine'&&!agent?<div className="empty-feed" data-testid="journal-no-agent"><BookOpen size={24}/><p>Your story is still unwritten.</p><span>Your journal begins when your agent arrives.</span></div>:list.length===0?<div className="empty-feed" data-testid="journal-empty"><Radio size={24}/><p>Waiting for the next field report.</p></div>:list.slice(0,more?40:expanded?12:4).map(e=><article className="journal-entry" data-testid={`journal-event-${e.id}`} key={e.id}><div className={`journal-avatar avatar-${e.avatar}`}><Avatar avatar={e.avatar} size={34}/></div><div className="journal-content"><div><b data-testid={`journal-name-${e.id}`}>{e.name}</b>{e.is_bot&&<span className="bot-tag">CREW BOT</span>}<span className={`event-stage stage-${e.stage}`}>{stageNames[e.stage]}</span></div><p data-testid={`journal-message-${e.id}`}>“{e.message}”</p></div><time dateTime={e.created_at} data-testid={`journal-time-${e.id}`}>{new Date(e.created_at).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',hour12:false})}</time></article>)}</div>
 {list.length>(expanded?12:4)&&<button className="text-button journal-more" data-testid="journal-show-more" onClick={()=>setMore(m=>!m)}>{more?'Show recent activity':'View more activity'}<ArrowUpRight size={13}/></button>}
 <div className="journal-bottom" data-testid="journal-source"><Filter size={12}/> Reports from the underground. Financial rewards are tracked separately.</div></section>;
};