import {useEffect,useState} from 'react';
import {Coins,ArrowUpRight,LockKeyhole,Info,ArrowRight,Clock3,ShieldCheck,ExternalLink,ReceiptText,Wallet,Scale} from 'lucide-react';
import {Link} from 'react-router-dom';
import {Button} from '../components/ui/button';
import {request} from './api';
import {Reward} from './types';
export const PoolPanel=()=> <section className="pool-panel" data-testid="mining-pool-panel"><div className="panel-heading"><div className="section-title"><Coins size={16}/><h2 data-testid="pool-panel-title">Mining Pool</h2></div><Link data-testid="pool-details-link" to="/rewards" title="Pool details" aria-label="Pool details"><ArrowUpRight size={16}/></Link></div><div className="pool-body"><div className="pool-label" data-testid="claimable-label">CLAIMABLE GLD <span className="gld-symbol">G</span></div><strong className="unavailable-value" data-testid="claimable-value">Not available</strong><span className="pool-status" data-testid="claimable-status">Awaiting contract verification</span><div className="pool-line"><span>Distribution period</span><span data-testid="distribution-period">24 hours</span></div><Button disabled data-testid="claim-gld-button" className="claim-button full-width"><LockKeyhole size={14}/>Claim GLD</Button><p className="pool-disclaimer" data-testid="pool-disclaimer"><Info size={12}/> Funded by received trading fees.<br/>No fixed or guaranteed returns.</p></div></section>;
export default function Rewards(){
 const [data,setData]=useState<Reward|null>(null),[error,setError]=useState('');
 useEffect(()=>{request<Reward>('/rewards').then(setData).catch(()=>setError('Pool information could not be loaded. Please refresh.'));},[]);
 return <div className="page-content"><div className="page-title"><div><div className="eyebrow" data-testid="rewards-eyebrow">TRANSPARENCY FIRST</div><h1 data-testid="rewards-title">The Mining Pool<span>.</span></h1><p data-testid="rewards-intro">A shared pool. A clear formula. Every allocation accounted for.</p></div><span className="neutral-badge" data-testid="reward-asset-badge"><Coins size={15}/>GLD · Robinhood Chain</span></div>
 {error&&<p className="error-banner" role="alert" data-testid="rewards-error">{error}</p>}<div className="verification-band" data-testid="contract-verification-notice"><ShieldCheck size={20}/><div><strong>Good things start with solid foundations.</strong><p>MINEPX has not launched. Pool funding and GLD claims open only after official contracts and fee mechanics are verified.</p></div><span>VERIFICATION PENDING</span></div>
 <div className="reward-metrics">{[{label:'Pool balance',icon:Coins,sub:'Verified, allocated GLD'},{label:'Estimated rewards',icon:Clock3,sub:'Current distribution period'},{label:'Claimable GLD',icon:Wallet,sub:'Finalized allocations only'}].map((m,i)=><section key={m.label} data-testid={`reward-metric-${i}`}><div className="metric-top"><m.icon size={18}/><span>{m.label}</span></div><strong>Not available</strong><small>{m.sub}</small>{i===2&&<Button disabled className="claim-button" data-testid="rewards-claim-button"><LockKeyhole size={14}/>Claim GLD</Button>}</section>)}</div>
 <div className="rewards-grid"><section className="formula-section"><div className="section-title"><Scale size={19}/><h2 data-testid="reward-formula-title">Fair by design</h2></div><p data-testid="reward-formula-description">Your share follows your holding balance over time, after your agent is activated.</p><div className="reward-formula" data-testid="reward-formula"><span>Your GLD</span><b>=</b><span>Available GLD</span><b>×</b><span className="fraction"><span>Your balance × holding time</span><span>Total eligible holding weight</span></span></div><div className="principle-grid">{[['24-hour periods','No daily login requirement.'],['No minimum holding','Small fractions accumulate with high precision.'],['Hold in your wallet','No staking, locks, or private key access.'],['Game progress stays separate','Ore, luck, cosmetics, and levels never change GLD shares.']].map(([title,text],i)=><div key={title} data-testid={`reward-principle-${i}`}><CheckIcon/><strong>{title}</strong><p>{text}</p></div>)}</div><p className="fine-print" data-testid="reward-eligibility-note">Selling your entire MINEPX balance stops future accrual, not previously recorded rights. Splitting holdings between wallets does not increase the combined share.</p></section>
 <section className="funding-section"><h2 data-testid="funding-title">Follow the funding</h2><dl>{[['Fee source','Pons trading fees · unverified'],['Fee denomination','Not available'],['Pool allocation','Not available'],['Fees received','Not available'],['Distribution period',data?`${data.period_hours} hours`:'Not available'],['Official GLD contract','Not available'],['Reward vault','Not available']].map(([k,v],i)=><div key={k} data-testid={`funding-detail-${i}`}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><a href="https://ponsfamily.com" target="_blank" rel="noreferrer" data-testid="pons-reference-link" className="text-button">Visit Pons<ExternalLink size={13}/></a></section></div>
 <section className="distribution-section"><div className="section-title"><ReceiptText size={18}/><h2 data-testid="distribution-title">Distribution ledger</h2><span className="neutral-badge">0 distributions</span></div><div className="ledger-empty" data-testid="distribution-empty"><ReceiptText size={28}/><h3>No distributions yet</h3><p>Confirmed funding, allocation records, and transaction references will appear here.</p></div></section><div className="reward-footnotes" data-testid="reward-risk-notice"><Info size={15}/><p>Only fees actually received and allocated can fund rewards. No new funding means no new rewards; with no eligible holders, funds carry forward. GLD is a Robinhood real-world-asset token, not physically mined gold. Availability depends on verification and jurisdiction. Off-chain calculations depend on the operator and are not fully trustless. No APY or returns are guaranteed.</p></div>
 </div>;
}
const CheckIcon=()=> <ShieldCheck size={16}/>;