import {useEffect,useState} from 'react';
import {Coins,ArrowUpRight,LockKeyhole,Info,Clock3,ShieldCheck,ExternalLink,ReceiptText,Wallet,Scale,Trophy} from 'lucide-react';
import {Link} from 'react-router-dom';
import {Button} from '../components/ui/button';
import {request} from './api';
import {Reward} from './types';
export const PoolPanel=()=> <section className="pool-panel" data-testid="mining-pool-panel"><div className="panel-heading"><div className="section-title"><Coins size={16}/><h2 data-testid="pool-panel-title">Holder Rewards</h2></div><Link data-testid="pool-details-link" to="/rewards" title="Holder reward details" aria-label="Holder reward details"><ArrowUpRight size={16}/></Link></div><div className="pool-body"><div className="pool-label" data-testid="claimable-label">CLAIMABLE GLD <span className="gld-symbol">G</span></div><strong className="unavailable-value" data-testid="claimable-value">Not available</strong><span className="pool-status" data-testid="claimable-status">Solana asset verification pending</span><div className="pool-line"><span>Distribution basis</span><span data-testid="distribution-period">Pro rata holdings</span></div><Button disabled data-testid="claim-gld-button" className="claim-button full-width"><LockKeyhole size={14}/>Claim GLD</Button><p className="pool-disclaimer" data-testid="pool-disclaimer"><Info size={12}/>Stonk.fun trading fees. Agent scores<br/>never change your holder share.</p></div></section>;
export default function Rewards(){
 const [data,setData]=useState<Reward|null>(null),[error,setError]=useState('');
 useEffect(()=>{request<Reward>('/rewards').then(setData).catch(()=>setError('Pool information could not be loaded. Please refresh.'));},[]);
 return <div className="page-content"><div className="page-title"><div><div className="eyebrow" data-testid="rewards-eyebrow">HOLDINGS, NOT HIGH SCORES</div><h1 data-testid="rewards-title">Holder rewards<span>.</span></h1><p data-testid="rewards-intro">Trading activity funds the pool. Your holdings determine your share.</p></div><span className="neutral-badge" data-testid="reward-asset-badge"><Coins size={15}/>GLD requested · Solana</span></div>
 {error&&<p className="error-banner" role="alert" data-testid="rewards-error">{error}</p>}<div className="verification-band" data-testid="contract-verification-notice"><ShieldCheck size={20}/><div><strong>The right asset. The right foundation.</strong><p>MINEPX has not launched. GLD remains the requested reward asset, subject to a verified official Solana mint and Stonk.fun support. GLDx listings are not treated as the same asset or silently substituted.</p></div><span>VERIFICATION PENDING</span></div>
 <div className="reward-metrics">{[{label:'Holder pool',icon:Coins,sub:'Verified, received trading fees'},{label:'Estimated rewards',icon:Clock3,sub:'Subject to verified distribution rules'},{label:'Claimable GLD',icon:Wallet,sub:'Finalized allocations only'}].map((m,i)=><section key={m.label} data-testid={`reward-metric-${i}`}><div className="metric-top"><m.icon size={18}/><span>{m.label}</span></div><strong>Not available</strong><small>{m.sub}</small>{i===2&&<Button disabled className="claim-button" data-testid="rewards-claim-button"><LockKeyhole size={14}/>Claim GLD</Button>}</section>)}</div>
 <div className="rewards-grid"><section className="formula-section"><div className="section-title"><Scale size={19}/><h2 data-testid="reward-formula-title">A proportional share</h2></div><p data-testid="reward-formula-description">Planned holder allocation is proportional to eligible MINEPX holdings under the verified Stonk.fun distribution rules. No agent activation, holding-time multiplier, or mining score is added.</p><div className="reward-formula" data-testid="reward-formula"><span>Your reward</span><b>=</b><span>Available pool</span><b>×</b><span className="fraction"><span>Your eligible MINEPX holdings</span><span>Total eligible MINEPX holdings</span></span></div><div className="principle-grid">{[['Hold, without playing','Creating or running an agent is not a holder-reward requirement.'],['No minimum planned','Platform eligibility and rounding still require verification.'],['No staking','No token locks or private key access.'],['No strategy multipliers','Ore, score, risk, and contest rank never increase holder shares.']].map(([title,text],i)=><div key={title} data-testid={`reward-principle-${i}`}><ShieldCheck size={16}/><strong>{title}</strong><p>{text}</p></div>)}</div><p className="fine-print" data-testid="reward-eligibility-note">Previously finalized allocations remain separate from future eligibility. No fixed bonus per wallet is added. Settlement timing, fees, eligibility, and rounding will follow verified platform mechanics—not browser scores.</p></section>
 <section className="funding-section"><h2 data-testid="funding-title">Follow the funding</h2><dl>{[['Network','Solana'],['Launch platform','Stonk.fun'],['Holder funding','Received trading fees'],['Fee denomination','Not available'],['Pool allocation','Not available'],['Distribution schedule',data?.period_hours?`${data.period_hours} hours`:'Awaiting verification'],['Official GLD mint','Not available'],['Settlement mechanism','Not available']].map(([k,v],i)=><div key={k} data-testid={`funding-detail-${i}`}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><a href="https://www.stonkfun.xyz" target="_blank" rel="noreferrer" data-testid="stonk-reference-link" className="text-button">Visit Stonk.fun<ExternalLink size={13}/></a></section></div>
 <section className="separate-rewards" data-testid="separate-contest-rewards"><div className="section-title"><Trophy size={20}/><h2>A different race. A separate prize.</h2></div><p>Agent contests rank mining strategy performance. Any contest prize will come from a separate project or sponsor pool, never the holder allocation. Prize amounts, assets, and funding are not yet announced.</p><Link className="text-button" to="/leaderboard" data-testid="rewards-contest-link">View the contest<ArrowUpRight size={14}/></Link></section>
 <section className="distribution-section"><div className="section-title"><ReceiptText size={18}/><h2 data-testid="distribution-title">Distribution ledger</h2><span className="neutral-badge" data-testid="distribution-count">0 distributions</span></div><div className="ledger-empty" data-testid="distribution-empty"><ReceiptText size={28}/><h3>No distributions yet</h3><p>Confirmed funding, allocation records, and transaction references will appear here.</p></div></section><div className="reward-footnotes" data-testid="reward-risk-notice"><Info size={15}/><p>Only received and allocated fees can fund rewards. No incoming fees means no new holder rewards. Solana asset authenticity, platform support, settlement mechanics, and jurisdiction restrictions must be verified before GLD is enabled. GLDx is a distinct candidate, not a confirmed replacement. No physical gold mining, APY, or returns are promised. Off-chain records depend on the operator and are not fully trustless.</p></div></div>;
}