import {ArrowUp,ArrowDown,Plus,Trash2,GitBranch} from 'lucide-react';
import {Rule,Group,Metric,metricNames,actionNames} from './strategyTypes';
const operators=[['lte','≤'],['lt','<'],['gte','≥'],['gt','>'],['eq','='],['neq','≠']];
export const RuleBuilder=({rules,onChange}:{rules:Rule[];onChange:(r:Rule[])=>void})=>{
 const replace=(index:number,value:Rule)=>onChange(rules.map((r,i)=>i===index?value:r));
 const move=(index:number,by:number)=>{const list=[...rules];[list[index],list[index+by]]=[list[index+by],list[index]];onChange(list);};
 const groupChange=(ri:number,gi:number,group:Group)=>replace(ri,{...rules[ri],groups:rules[ri].groups.map((g,i)=>i===gi?group:g)});
 return <section className="rule-builder" data-testid="rule-builder"><div className="strategy-section-heading"><div><div className="section-title"><GitBranch size={18}/><h2 data-testid="rule-builder-title">Decision rules</h2></div><p data-testid="rule-priority-note">First matching rule wins. Safety overrides remain in place.</p></div><span className="neutral-badge" data-testid="rule-count">{rules.length} / 8</span></div>
 {rules.map((rule,ri)=><article className={`strategy-rule ${rule.enabled?'':'rule-disabled'}`} key={rule.id} data-testid={`strategy-rule-${ri}`}><div className="rule-heading"><span className="rule-index" data-testid={`rule-priority-${ri}`}>{String(ri+1).padStart(2,'0')}</span><input aria-label={`Rule ${ri+1} name`} data-testid={`rule-name-${ri}`} value={rule.name} maxLength={36} onChange={e=>replace(ri,{...rule,name:e.target.value})}/><label className="rule-toggle"><input data-testid={`rule-enabled-${ri}`} type="checkbox" checked={rule.enabled} onChange={e=>replace(ri,{...rule,enabled:e.target.checked})}/><span>Active</span></label><div className="rule-tools"><button type="button" data-testid={`rule-up-${ri}`} title="Move rule up" aria-label="Move rule up" disabled={!ri} onClick={()=>move(ri,-1)}><ArrowUp size={14}/></button><button type="button" data-testid={`rule-down-${ri}`} title="Move rule down" aria-label="Move rule down" disabled={ri===rules.length-1} onClick={()=>move(ri,1)}><ArrowDown size={14}/></button><button type="button" data-testid={`rule-delete-${ri}`} title="Delete rule" aria-label="Delete rule" onClick={()=>onChange(rules.filter((_,i)=>i!==ri))}><Trash2 size={14}/></button></div></div>
 <div className="rule-content"><div className="rule-logic"><span>IF</span><select data-testid={`rule-match-${ri}`} aria-label="Match condition groups" value={rule.match} onChange={e=>replace(ri,{...rule,match:e.target.value as 'all'|'any'})}><option value="all">ALL groups match</option><option value="any">ANY group matches</option></select></div>
 {rule.groups.map((group,gi)=><div className="condition-group" key={gi} data-testid={`rule-group-${ri}-${gi}`}><div className="group-heading"><span>GROUP {gi+1}</span><select data-testid={`group-match-${ri}-${gi}`} aria-label="Match conditions" value={group.match} onChange={e=>groupChange(ri,gi,{...group,match:e.target.value as 'all'|'any'})}><option value="all">ALL conditions</option><option value="any">ANY condition</option></select>{rule.groups.length>1&&<button type="button" data-testid={`group-remove-${ri}-${gi}`} title="Remove group" aria-label="Remove group" onClick={()=>replace(ri,{...rule,groups:rule.groups.filter((_,i)=>i!==gi)})}><Trash2 size={12}/></button>}</div>
 {group.conditions.map((c,ci)=><div className="rule-condition" key={ci}><select aria-label="Condition metric" data-testid={`condition-field-${ri}-${gi}-${ci}`} value={c.field} onChange={e=>{const field=e.target.value as Metric;groupChange(ri,gi,{...group,conditions:group.conditions.map((item,i)=>i===ci?{...item,field,value:field==='depth'?Math.max(1,Math.min(5,item.value)):item.value}:item)});}}>{Object.entries(metricNames).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select><select aria-label="Comparison operator" data-testid={`condition-op-${ri}-${gi}-${ci}`} value={c.operator} onChange={e=>groupChange(ri,gi,{...group,conditions:group.conditions.map((item,i)=>i===ci?{...item,operator:e.target.value as typeof c.operator}:item)})}>{operators.map(([key,label])=><option value={key} key={key}>{label}</option>)}</select><div className="condition-number"><input aria-label="Condition threshold" data-testid={`condition-value-${ri}-${gi}-${ci}`} type="number" min={c.field==='depth'?1:0} max={c.field==='depth'?5:100} value={c.value} onChange={e=>groupChange(ri,gi,{...group,conditions:group.conditions.map((item,i)=>i===ci?{...item,value:Number(e.target.value)}:item)})}/><span>{c.field==='depth'?'LVL':'%'}</span></div><button type="button" data-testid={`condition-remove-${ri}-${gi}-${ci}`} title="Remove condition" aria-label="Remove condition" disabled={group.conditions.length===1} onClick={()=>groupChange(ri,gi,{...group,conditions:group.conditions.filter((_,i)=>i!==ci)})}><Trash2 size={13}/></button></div>)}
 {group.conditions.length<4&&<button type="button" className="text-button" data-testid={`condition-add-${ri}-${gi}`} onClick={()=>groupChange(ri,gi,{...group,conditions:[...group.conditions,{field:'energy',operator:'gte',value:40}]})}><Plus size={12}/>Condition</button>}</div>)}
 {rule.groups.length<3&&<button type="button" className="text-button add-group" data-testid={`group-add-${ri}`} onClick={()=>replace(ri,{...rule,groups:[...rule.groups,{match:'all',conditions:[{field:'cargo',operator:'gte',value:50}]}]})}><Plus size={12}/>Condition group</button>}
 <div className="rule-action"><span>THEN</span><select aria-label="Rule action" data-testid={`rule-action-${ri}`} value={rule.action} onChange={e=>replace(ri,{...rule,action:e.target.value})}>{Object.entries(actionNames).filter(([key])=>key!=='refine').map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></div></div></article>)}
 <button type="button" className="add-rule-button" data-testid="strategy-add-rule" disabled={rules.length>=8} onClick={()=>onChange([...rules,{id:crypto.randomUUID(),name:`Custom rule ${rules.length+1}`,enabled:true,match:'all',groups:[{match:'all',conditions:[{field:'energy',operator:'lte',value:30}]}],action:'rest'}])}><Plus size={16}/>Add decision rule</button>
 </section>;
};